test(artifact_collector): add typing to test_preprocess_artifacts.py
Samsung/Universum pull request #754
Opened 2023-01-19 05:48 UTC by miltolstoy

2023-01-19 05:49 UTC, miltolstoy commented on tests/test_preprocess_artifacts.py
> +class ArtifactsTestEnvironment(LocalTestEnvironment):
The logic was not changed. 
Code was moved to declare the `ArtifactsTestEnvironment` before usage.
Typing was added here too.

2023-01-19 07:46 UTC, i-keliukh requested changes
Please fix pylint issues

2023-01-20 15:59 UTC, i-keliukh commented on tests/test_preprocess_artifacts.py
> +            content: str = f.read().replace("\n", "")
note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs

2023-01-21 08:04 UTC, k-dovgan commented on nohup.out
> +CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
Is this file supposed to be in repo? Why?

2023-01-23 07:34 UTC, i-keliukh approved these changes

2023-01-23 07:39 UTC, merged