fix(checks): MyPy and Pylint warnings
Samsung/Universum pull request #755
Opened 2023-01-19 15:36 UTC by k-dovgan

Also turn on failing on failed steps for better GhA reporting

2023-01-19 19:41 UTC, miltolstoy reviewed
LGTM

2023-01-20 06:54 UTC, i-keliukh requested changes
Please fix mypy warnings as well

2023-01-20 08:53 UTC, i-keliukh commented on tests/utils.py
> +        self.root_directory: py.path.local  # type: ignore
In my opinion it would be much better to annotate the function than to suppress warning. The warning is valid.

2023-01-20 08:54 UTC, i-keliukh commented on universum/modules/reporter.py
> +        self.code_report_comments: Dict[str, List[ReportMessage]] = defaultdict(list)  # type: ignore
Same issue: it is better to annotate function than to ignore warning

2023-01-20 08:54 UTC, i-keliukh commented on universum/modules/vcs/perforce_vcs.py
> +        self.unshelved_files: List[Dict[str, str]] = []  # type: ignore
Same issue

2023-01-20 14:03 UTC, i-keliukh approved these changes

2023-01-20 14:24 UTC, merged