fix(workflow): wrong inline comments processing
Samsung/Universum pull request #811
Opened 2023-05-30 13:54 UTC by k-dovgan

2023-05-30 14:06 UTC, k-dovgan commented on .github/workflows/telegram-bot.yml
> +    types: [created]
Second test.

2023-05-30 14:06 UTC, k-dovgan commented
Other test.

2023-05-30 14:34 UTC, i-keliukh commented on .github/workflows/telegram-bot.yml
> +          if [[ ! -z "${{ github.event.pull_request }}" ]]; then
Test 1

2023-05-30 19:22 UTC, i-keliukh commented
Test 3

2023-05-30 19:23 UTC, i-keliukh commented on .github/workflows/telegram-bot.yml
> +    name: print payload
Test 4

2023-05-30 19:23 UTC, i-keliukh requested changes
Test 5

2023-05-30 19:24 UTC, i-keliukh reviewed
Test 6

2023-05-30 19:50 UTC, k-dovgan commented on .github/workflows/telegram-bot.yml
> +  pull_request_review_comment:
Try adding path.

2023-05-30 19:51 UTC, k-dovgan reviewed
This is review comment.

2023-05-31 14:36 UTC, miltolstoy approved these changes

2023-06-01 08:51 UTC, i-keliukh approved these changes

2023-06-01 08:53 UTC, merged